// <auto-generated />
using FoodOrderApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230111072003_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FoodOrderApp.Shared.Menus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("FoodOrderApp.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenusId")
                        .HasColumnType("int");

                    b.Property<string>("NoOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorMeja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenusId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenusId = 1,
                            NoOrder = "ABC1",
                            NomorMeja = "1"
                        },
                        new
                        {
                            Id = 2,
                            MenusId = 2,
                            NoOrder = "ABC2",
                            NomorMeja = "2"
                        },
                        new
                        {
                            Id = 3,
                            MenusId = 1,
                            NoOrder = "ABC3",
                            NomorMeja = "3"
                        });
                });

            modelBuilder.Entity("FoodOrderApp.Shared.Order", b =>
                {
                    b.HasOne("FoodOrderApp.Shared.Menus", "Menus")
                        .WithMany()
                        .HasForeignKey("MenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
